# Generated by Django 4.2.1 on 2023-05-22 00:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_prestamolibro_socio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo_Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=datetime.date.today)),
                ('fecha_devolucion', models.DateField(default=datetime.date.today)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.empleado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.socio')),
            ],
        ),
        migrations.DeleteModel(
            name='PrestamoLibro',
        ),
    ]
