# Generated by Django 4.2.1 on 2023-05-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_prestamo_libro_delete_prestamolibro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prestamo_Libro',
            new_name='PrestamoLibro',
        ),
    ]
