from django.urls import path

from .views import (
    activar_autor,
    activar_empleado,
    activar_libro,
    activar_socio,
    actualizar_autores,
    actualizar_datos_empleado,
    actualizar_datos_socio,
    actualizar_libro,
    actualizar_prestamo,
    desactivar_autor,
    desactivar_empleado,
    desactivar_libro,
    desactivar_socio,
    eliminar_empleado,
    eliminar_prestamo_libro,
    listar_autores,
    listar_empleados,
    listar_libros,
    listar_prestamos,
    listar_socios,
    nuevo_autores,
    nuevo_libro,
    nuevo_socio,
    registrar_empleado,
    registrar_prestamo
)

urlpatterns = [
    path('empleados/registrar',registrar_empleado, name='registrar_empleado'),
    path('empleados/desactivar/<int:id>', desactivar_empleado, name='desactivar_empleado'),
    path('empleados/activar/<int:id>', activar_empleado, name='activar_empleado'),
    path('empleados/eliminar/<int:id>', eliminar_empleado, name='eliminar_empleado'),
    path('empleados/listado/', listar_empleados, name='listado_empleados'),
    path('empleados/actualizar/<int:empleado_id>', actualizar_datos_empleado, name='actualizar_empleado'),
    path('autores/desactivar/<int:autor_id>', desactivar_autor, name='desactivar_autor'),
    path('autores/nuevo/', nuevo_autores, name='nuevo_autores'),
    path('autores/actualizar/<int:autor_id>/', actualizar_autores, name='actualizar_autores'),
    path('autores/activar/<int:autor_id>/', activar_autor, name='activar_autor'),
    path('autores/listado/', listar_autores, name='listado_autores'),
    path('socios/nuevo/', nuevo_socio, name='nuevo_socio'),
    path('socios/listado/', listar_socios, name='listado_socios'),
    path('socios/actualizar/<int:socio_id>',actualizar_datos_socio,name='actualizar_datos_socio'),
    path('socios/activar/<int:id>',activar_socio,name='activar_socio'),
    path('socios/desactivar/<int:id>',desactivar_socio,name='desactivar_socio'),
    path('prestamos/eliminar/<int:prestamo_id>', eliminar_prestamo_libro, name='eliminar_prestamo_libro'),
    path('libros/activar/<int:id>', activar_libro, name='activar_libro'),
    path('libros/nuevo/', nuevo_libro, name='nuevo_libro'),
    path('libros/listado/',listar_libros, name='listado_libros'),
    path('libros/desactivar/<int:id>', desactivar_libro, name='desactivar_libro'),
    path('libros/actualizar/<int:id>', actualizar_libro, name='actualizar_libro'),
    path('prestamos/nuevo/', registrar_prestamo, name='registrar_prestamo'),
    path('prestamos/listado/',listar_prestamos, name='listado_prestamos'),
    path('prestamos/actualizar/<int:id>',actualizar_prestamo, name='actualizar_prestamo'),


]